version: "3.6"

services:
  library:
    container_name: ${PROJECT_NAME}_library
    image: openizr/node:4.0.0-dev
    env_file:
      - .env
    command: sh -c "
      dsync src/scripts/main.d.ts dist/main.d.ts &
      dsync src/scripts/react.d.ts dist/react.d.ts &
      dsync src/scripts/vue.d.ts dist/vue.d.ts &
      dsync src/scripts/svelte.d.ts dist/svelte.d.ts &
      yarn && yarn run dev"
    volumes:
      - ./library:/var/www/html
      - ./:/mount
    restart: unless-stopped
  examples:
    container_name: ${PROJECT_NAME}_examples
    image: openizr/node:4.0.0-dev
    user: node:node
    env_file:
      - .env
    ports:
      - "${HOST_IP}:${EXAMPLES_PORT}:${EXAMPLES_PORT}"
    command: sh -c "dsync /library/dist/ node_modules/biuty/"
    working_dir: /var/www/html
    volumes:
      - ./library:/library
      - ./examples:/var/www/html
    restart: unless-stopped

# For people that use a VPN
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.78.0/24
