version: "3.6"

services:
  library:
    container_name: ${PROJECT_NAME}_library
    image: openizer/node:1.1.0-dev
    env_file:
      - .env
    command: sh -c "yarn && dsync src/styles/core/ dist/core/ & yarn run dev"
    volumes:
      - ./library:/var/www/html
    restart: on-failure
  playground:
    container_name: ${PROJECT_NAME}_playground
    image: openizer/node:1.1.0-dev
    env_file:
      - .env
    ports:
      - "127.0.0.1:${PLAYGROUND_PORT}:${PLAYGROUND_PORT}"
    working_dir: /var/www/html/react
    command: sh -c "yarn && dsync /sonar-ui/dist/ node_modules/sonar-ui/ & yarn run dev"
    volumes:
      - ./playground:/var/www/html
      - ./library:/sonar-ui
    restart: on-failure
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
